services:
  # The app itself (prod only, soon testing)
  # Partial support for nginx 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./nginx/certs:/ssl:ro
      - ${PWD_PATH}:/auth:ro
    depends_on:
      - frontend
      - backend
      - database
      - grafana
      - backend-testing
      - frontend-testing
      - database-testing    
    networks:
      - app-network
  
  backend:
    image: ${DOCKER_USER}/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks: 
      - app-network
    depends_on:
      - database
    env_file:
      - .env
  
   backend-testing:
    image: ${DOCKER_USER}/backend-testing:latest
    container_name: backend-testing
    ports:
      - "8081:8081"
    networks:
      - app-network
    depends_on:
      - frontend
      - database-testing
    env_file:
      - .env
   
  frontend:
    image: ${DOCKER_USER}/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    networks: 
      - app-network


 frontend-testing:
    image: ${DOCKER_USER}/frontend-testing:latest
    container_name: frontend-testing
    ports:
      - "3001:3001"
    depends-on:
      - backend-testing    
    networks:
      - app-network

  database:
    image: postgres:latest
    container_name: database-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks: 
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
  

  database-testing:
    image: postgres:latest
    container_name: database-testing
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TESTING}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5433"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d

  # Monitoring
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "9999:9999"
    env_file:
      - .env
    volumes:
      - ./monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - app-network
    restart: unless-stopped 

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network
    restart: unless-stopped

  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml
    volumes:
      - ./monitoring:/mnt/config
    networks:
      - app-network
    restart: unless-stopped

  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail
    volumes:
      - ./monitoring:/mnt/config
      - /var/log:/var/log
    command: -config.file=/mnt/config/promtail-config.yaml
    depends_on:
      - loki
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  grafana-storage:
  prometheus-data:
