services:
  # Partial support for nginx 
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx:ro
    depends_on:
      - frontend
      - backend
      - database
    networks:
      - app-network

  backend:
    image: ${DOCKER_USER}/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    networks: 
      - app-network
    depends_on:
      - database
    env_file:
      - .env
    
  frontend:
    image: ${DOCKER_USER}/frontend:latest
    container_name: frontend
    ports:
      - "3000:3000"
    networks: 
      - app-network
    depends_on:
      - backend

  database:
    image: postgres:latest
    container_name: database-prod
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks: 
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init_processed.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
