services:
  # let them commented until the 3 docker containers are up and running
  #nginx:
  #image: nginx:latest
  #ports:
    #- "80:80"
    #- "443:443"
  #volumes:
    #- ./nginx/conf.d:/etc/nginx/conf.d:ro
    #- ./nginx/certs:/etc/nginx/certs:ro  # For SSL later on
  #depends_on:
    #- frontend
    #- backend
    #- database
  #networks:
    #- app-network

  backend:
    image: ${DOCKER_USER}/backend:latest
    ports:
      - "8080:8080"
    networks: 
      - app-network
    depends_on:
      - database
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

  frontend:
    image: ${DOCKER_USER}/frontend:latest
    ports:
      - "3000:3000"
    networks: 
      - app-network
    #depends_on:
     # - backend

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks: 
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
